version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/database.sqlite
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - backend_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - deepsim-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - deepsim-network

  # Optional: Database management UI
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/data
    command: ["sqlite_web", "/data/database.sqlite", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - backend
    networks:
      - deepsim-network

volumes:
  backend_data:

networks:
  deepsim-network:
    driver: bridge