name: deepsim
channels:
  - conda-forge
dependencies:
  # Python version
  - python=3.10
  - pip
  
  # Core Web Framework
  - nodejs=18
  - npm
  
  # Scientific Computing
  - numpy
  - pandas
  - scipy
  - matplotlib
  - plotly
  
  # Database
  - sqlite
  
  # Development Tools
  - jupyter
  - ipykernel
  
  # Testing
  - pytest
  
  # Utilities
  - pyyaml
  - python-dotenv
  
  # Pip dependencies
  - pip:
    # FastAPI Backend
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.20.0
    - pydantic>=2.0.0
    - python-multipart
    - aiofiles
    - httpx
    - python-jose[cryptography]
    - passlib[bcrypt]
    
    # Chemical Process Simulation
    - pyomo>=6.0.0
    - idaes-pse>=2.0.0
    
    # LLM Integration (optional - for Thunder Compute)
    - transformers
    - torch
    - accelerate